import { siteConfig } from "./site";

export const defaultSeo = {
  title: siteConfig.title,
  description: siteConfig.description,
  canonical: siteConfig.url,
  // OG/Twitter images are generated by app/opengraph-image.tsx and app/twitter-image.tsx
  // (file-based metadata), so no image URLs are hardcoded here.
  openGraph: {
    type: "website" as const,
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.title,
    description: siteConfig.description,
  },
  twitter: {
    card: "summary_large_image" as const,
    title: siteConfig.title,
    description: siteConfig.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1 as const,
      "max-image-preview": "large" as const,
      "max-snippet": -1 as const,
    },
  },
};

export type SeoConfig = typeof defaultSeo;
