import { siteConfig } from "./site";

export const defaultSeo = {
  title: siteConfig.title,
  description: siteConfig.description,
  canonical: siteConfig.url,
  // OG/Twitter images are generated by app/opengraph-image.tsx and app/twitter-image.tsx
  // (file-based metadata), so no image URLs are hardcoded here.
  openGraph: {
    type: "website" as const,
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.title,
    description: siteConfig.description,
  },
  twitter: {
    card: "summary_large_image" as const,
    title: siteConfig.title,
    description: siteConfig.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1 as const,
      "max-image-preview": "large" as const,
      "max-snippet": -1 as const,
    },
  },
};

export type SeoConfig = typeof defaultSeo;

/**
 * Per-page defaults, used when no admin SEO override is saved (or a field is
 * left empty). The admin SEO editor shows these as placeholders.
 */
export const pageSeoDefaults = {
  home: { title: siteConfig.title, description: siteConfig.description },
  projects: {
    title: "Projects",
    description: `A showcase of software projects built by ${siteConfig.name}.`,
  },
  about: {
    title: "About",
    description: `Learn more about ${siteConfig.name} — skills, experience, education, and background.`,
  },
  contact: {
    title: "Get in Touch",
    description: `Contact ${siteConfig.name} for collaboration, job opportunities, or general inquiries.`,
  },
} as const;
